services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: showcase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5443:5432"
    networks:
      - app-network

  spring:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/showcase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
