spring:
    config:
        import: optional:file:env.properties
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: ${CLIENT_ID}
                        clientSecret: ${CLIENT_SECRET}