spring:
    application:
        name: showcase

    config:
        import: optional:file:env.properties

    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: ${CLIENT_ID}
                        clientSecret: ${CLIENT_SECRET}

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update